name: Test action
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: date > foo.md
      - name: Exeicise
        id: exeicise
        uses: ./
        with:
          message: Test
      - name: Verify
        run: |
          set -x
          test "$(gh pr view "${BRANCH}" --json title --jq .title)" = "Test"
        env:
          BRANCH: ${{steps.exeicise.outputs.branch}}
      - name: Teardown
        if: ${{always()}}
        run: |
          gh pr close "${BRANCH}" || true
          git push origin "${BRANCH}" --delete || true
        env:
          BRANCH: ${{steps.exeicise.outputs.branch}}